name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.6.0
  go_router: ^8.0.2
  google_fonts: ^5.0.0
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/flickrfames-icon-one.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/
