name: noteshop
description: Noteshop is a Dart/Flutter app designed to enhance your shopping experience. Integrated with the Teslo Shop backend, this app leverages Riverpod, Go Router, and CRUD REST API endpoints to provide a seamless shopping journey. With Noteshop, you can effortlessly browse and purchase products while enjoying the ability to add notes to your products.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.3.2
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_plugin_android_lifecycle: ^2.0.15
  flutter_riverpod: ^2.3.7
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.5
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_two.png"
  min_sdk_android: 21
  adaptive_icon_background: "#f7f7f7"


flutter_native_splash:
  color: "#282828"
  image: assets/icon/logo_inverted.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/


# fonts:
#   - family: MaterialIcons
#     fonts:
#       - asset: packages/material_design_icons_flutter/fonts/MaterialIcons-Regular.otf
#         package: material_design_icons_flutter
